CREATE DATABASE crud;
USE crud;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  sobrenome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  genero VARCHAR (100) NOT NULL,
  anoNascimento INT,
  cpf VARCHAR(11)
);

INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jazmyne', 'West', 'Robin23@yahoo.com', 'Transexual female', '2002', '22707-7030');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cortney', 'Farrell', 'Oma.Robel@hotmail.com', 'Trigender', '1994', '92119');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cora', 'Lind', 'Hortense.Harber66@yahoo.com', 'Female to male trans man', '1937', '70105');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brenda', 'Champlin', 'Elisabeth_Dickinson80@hotmail.com', 'Gender questioning', '2010', '21404');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Deshaun', 'Schuppe', 'Deven_Buckridge94@gmail.com', 'Agender', '1941', '47475-0200');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adela', 'Krajcik', 'Grayson_King@gmail.com', 'Androgynous', '1946', '61674-1869');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eliane', 'Larkin', 'Sarai.Hartmann-Franecki@hotmail.com', 'Female to male trans man', '1960', '77257');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Modesta', 'Bashirian', 'Christophe.Goyette-Herman13@hotmail.com', 'T* woman', '1943', '80268-0429');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ella', 'Bauch-Fisher', 'Autumn.Schaefer64@hotmail.com', 'Cisgender', '2021', '14565-2798');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sally', 'Oberbrunner', 'Milan_Hammes71@hotmail.com', 'Androgyne', '1928', '93492-1672');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lorenzo', 'Leuschke', 'Hermann_Jerde@gmail.com', 'Cisgender', '1988', '12012');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Theresa', 'Schumm', 'Spencer47@yahoo.com', 'Agender', '1977', '19780');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brandy', 'Koch', 'Giuseppe_Koch@hotmail.com', 'Gender nonconforming', '1951', '69398');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Horace', 'Kirlin', 'Myrtice.Dietrich53@yahoo.com', 'Trans female', '1948', '74979');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ken', 'Daugherty', 'Norma.Stehr16@yahoo.com', 'Hermaphrodite', '1923', '69358');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Della', 'Keebler', 'Priscilla.Denesik@gmail.com', 'Trigender', '1988', '32042');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Morgan', 'Klein', 'Damion.Welch16@gmail.com', 'Intersex man', '1956', '93279-9386');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Courtney', 'Hand', 'Zachariah.Sipes89@gmail.com', 'Cis', '1951', '57661');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nannie', 'Rau', 'Delphine.Weber@gmail.com', 'Male to female trans woman', '2021', '50739-3349');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Myles', 'Little', 'Julio.Durgan@gmail.com', 'Demi-woman', '1983', '70092');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adela', 'Moore', 'Stevie11@hotmail.com', 'Male to female', '1963', '88659');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Helga', 'Howell', 'Martine.Gusikowski@hotmail.com', 'MTF', '1925', '38181');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ignatius', 'Dicki', 'Gustave_Casper@yahoo.com', 'Intersex woman', '1922', '48919-3108');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Leila', 'Wyman', 'Bobbie_Cartwright@gmail.com', 'Cis', '1992', '19001');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Willow', 'Rodriguez', 'Hoyt.Yundt@hotmail.com', 'Demi-girl', '1986', '56473-9873');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kristian', 'Towne', 'Gregg_Metz30@gmail.com', 'Trigender', '1975', '86908-6877');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Erica', 'Nienow', 'Delta.Hyatt32@yahoo.com', 'Trans female', '1958', '52501');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aleen', 'Goodwin', 'Katarina_Hudson99@gmail.com', 'Demigender', '1965', '67268');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kane', 'Bahringer', 'Alison_Reinger50@yahoo.com', 'Pangender', '1984', '45766-7527');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sarah', 'Quigley', 'Jaylen.Pacocha52@yahoo.com', 'Intersex person', '1920', '79519');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kaci', 'Doyle-Huels', 'Brock.Flatley71@yahoo.com', 'Trans', '1952', '62622-8845');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nia', 'Roberts', 'Abner.Roob31@gmail.com', 'Two-spirit', '2006', '50762-9549');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mozelle', 'Runolfsson', 'Sarah_Collins@gmail.com', 'Transgender person', '1953', '27059');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eliza', 'Rice', 'Luigi77@hotmail.com', 'Cis female', '1954', '62663');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gardner', 'Koepp-Boyle', 'Brett75@gmail.com', 'Multigender', '1968', '53233-9354');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lessie', 'Gerhold', 'Estevan_Wyman@hotmail.com', 'Transgender female', '1927', '94594');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aurore', 'Graham', 'Jay14@gmail.com', 'Other', '1923', '32748');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kelsie', 'Morar', 'Brooke59@hotmail.com', 'Demi-man', '2018', '03302-2688');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Fred', 'Bergstrom', 'Stephen_Jakubowski@yahoo.com', 'Gender variant', '1987', '15632-6858');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Agustina', 'Mueller', 'Naomi46@yahoo.com', 'Female to male transsexual man', '1988', '70381-2562');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alvena', 'Roob', 'Dorian_Oberbrunner81@gmail.com', 'Trans male', '2005', '15172');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marta', 'Moen', 'Ladarius44@gmail.com', 'Androgyne', '1959', '85730-0978');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lonzo', 'Swift', 'Keanu79@yahoo.com', 'Trans male', '1973', '68693-8546');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Harrison', 'Sanford', 'Arnold_Halvorson@yahoo.com', 'Gender variant', '1947', '90777');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Simone', 'Braun-Nitzsche', 'Celestine.Lebsack@gmail.com', 'Female to male transgender man', '1981', '51233');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Johnnie', 'Hickle', 'Levi_Lakin32@hotmail.com', 'Neither', '1930', '79068-7633');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Woodrow', 'Brakus', 'Caesar.Quigley@yahoo.com', 'Gender nonconforming', '1960', '45168');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lillie', 'Schulist', 'Jerel.Mueller@hotmail.com', 'Gender fluid', '2020', '71328-1938');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jabari', 'Sipes', 'Carole36@gmail.com', 'Pangender', '1942', '51792');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rogelio', 'Paucek', 'Remington44@hotmail.com', 'Woman', '1962', '81437-7435');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gerardo', 'Jaskolski', 'Katelin.Durgan32@gmail.com', 'M2F', '1953', '29590');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Elisa', 'Funk', 'Ansley_Quitzon@gmail.com', 'Trans female', '1980', '42890-3633');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jessyca', 'West', 'Leonie_Boehm83@gmail.com', 'Female to male trans man', '1951', '89476');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jess', 'Kohler', 'Pat.Ratke46@gmail.com', 'Transexual person', '2020', '89955-3867');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maritza', 'Walsh-Moen', 'Ronaldo_Littel@gmail.com', 'Transmasculine', '2003', '40198-7668');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Claudine', 'Emard', 'Ansley_Gottlieb@yahoo.com', 'Xenogender', '1954', '30479');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cole', 'Murazik', 'Bonnie.Kassulke89@yahoo.com', 'Transgender female', '1977', '32040');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brycen', 'Kulas', 'Issac.Lockman@hotmail.com', 'Woman', '1944', '31101');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Deven', 'Green', 'Darwin.Beatty90@gmail.com', 'Omnigender', '2008', '08137-7702');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Liza', 'Gislason', 'Fern.Dicki3@gmail.com', 'Non-binary', '2015', '89027');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aidan', 'Walsh', 'Delia_Nienow96@hotmail.com', 'Trans person', '1970', '59146-8106');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Davion', 'Bechtelar', 'Oswaldo64@hotmail.com', 'F2M', '1924', '53447-2657');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Savannah', 'Heaney', 'Ambrose65@hotmail.com', 'Cis man', '1964', '94925');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Israel', 'Nikolaus', 'Israel.Sauer@hotmail.com', 'Transmasculine', '1947', '07699');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jeffery', 'Legros', 'Albert.Rosenbaum@gmail.com', 'Transexual female', '2009', '21486-7911');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lilly', 'Kuhlman', 'Elwin61@hotmail.com', 'Transexual male', '1972', '30389');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Della', 'Feest', 'Cornell.Block@yahoo.com', 'Transmasculine', '1987', '73226');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Guillermo', 'Fritsch-Schroeder', 'Madge.Rath@hotmail.com', 'Demi-man', '2016', '76071-5012');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Chadrick', 'Durgan', 'Jayda_Fritsch32@yahoo.com', 'Xenogender', '2018', '48753');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Luther', 'Doyle', 'Quentin99@hotmail.com', 'MTF', '1969', '27587');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Herminio', 'Walsh', 'Andy.Frami@hotmail.com', 'Female to male', '2003', '99132-1262');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alexandro', 'Beer-Swift', 'Walter55@yahoo.com', 'Transexual woman', '1968', '76901');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bethany', 'Prosacco', 'Lucinda31@gmail.com', 'Intersex woman', '1996', '33345');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Trinity', 'Denesik', 'Fabian.Bergstrom38@gmail.com', 'Agender', '1977', '24386');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Deangelo', 'Pfannerstill', 'Aletha_Cruickshank@yahoo.com', 'Two-spirit person', '1964', '34400-9950');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alfonzo', 'Runolfsdottir', 'Leonie77@yahoo.com', 'Androgynous', '1956', '95452-0541');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Estella', 'Braun', 'Freida96@gmail.com', 'Demi-girl', '1938', '70123-8390');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lincoln', 'Halvorson', 'Kaia_Thiel18@hotmail.com', 'Demi-girl', '1939', '19589-0237');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Herta', 'Balistreri', 'Everardo_Mohr86@hotmail.com', 'Cis man', '1933', '88132');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Johnathon', 'Moore', 'Adrian_Torphy@hotmail.com', 'Trans female', '1949', '02121-7767');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Destinee', 'Larkin', 'Mustafa30@yahoo.com', 'Male to female transgender woman', '1921', '54982-7251');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Vilma', 'Fisher', 'Ari95@yahoo.com', 'Transexual man', '1973', '45238-8883');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lindsay', 'Rowe', 'Jannie47@hotmail.com', 'Other', '1965', '50126');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Oliver', 'Bartell', 'Pearline.Nitzsche90@hotmail.com', 'Male to female', '1945', '45287-0766');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Boyd', 'Kreiger', 'Veda89@hotmail.com', 'T* man', '1986', '28333');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Esther', 'Fadel', 'Pete47@gmail.com', 'Gender fluid', '1947', '40834');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Harmony', 'Ruecker', 'Olaf.Streich41@yahoo.com', 'Cisgender female', '1944', '51904');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lyla', 'Feeney-McCullough', 'Malinda_Sawayn@yahoo.com', 'Transexual woman', '1936', '17966');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marcia', 'Shanahan', 'Tate_Heaney98@hotmail.com', 'Cis male', '1935', '31077-7433');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Vita', 'Dach', 'Horace92@gmail.com', 'Transexual woman', '2001', '84005-1129');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kitty', 'Glover', 'Kurtis_Adams@gmail.com', 'Gender questioning', '1947', '44880-5043');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ben', 'Nicolas', 'Darion.Welch@gmail.com', 'MTF', '2023', '71537');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ernie', 'Okuneva', 'Marjory2@hotmail.com', 'Transexual man', '1976', '87984-5087');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Desmond', 'Nicolas-DuBuque', 'Nona9@yahoo.com', 'Bigender', '1987', '57591-8575');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Fritz', 'Mayert', 'Lyda_Hoeger@yahoo.com', 'Female to male trans man', '1929', '26873');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Justina', 'Boyle', 'Isaiah_Ledner@gmail.com', 'Cisgender male', '2022', '75882-5607');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sandra', 'Kirlin', 'Tod16@yahoo.com', 'Intersex', '1938', '96538');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adrain', 'Beatty', 'Marco_Kihn55@gmail.com', 'Non-binary', '1999', '87342');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Amely', 'Bradtke', 'Tamara.Koch60@yahoo.com', 'T* woman', '1952', '06966-7925');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Michaela', 'Hills-Hickle', 'Octavia88@gmail.com', 'Transexual female', '1956', '61386-5641');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kian', 'Sawayn', 'Payton_Raynor@gmail.com', 'Trans', '1968', '09387');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Etha', 'Ritchie', 'Dandre27@yahoo.com', 'Transexual woman', '1957', '38194');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Darrick', 'Douglas', 'Guillermo.Lynch56@hotmail.com', 'Trans woman', '2017', '68603');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Florian', 'Effertz-Sauer', 'Marlene_Pacocha@hotmail.com', 'Genderflux', '1935', '13415-8310');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kaleigh', 'Gusikowski', 'Kylie_Bahringer@yahoo.com', 'Two-spirit person', '1938', '78190-3491');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alf', 'Crona', 'Beau.Leffler0@gmail.com', 'Hermaphrodite', '1987', '04920-4721');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alexie', 'Torphy', 'Eloise.Hickle@gmail.com', 'Hermaphrodite', '1935', '81962');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Catherine', 'Sauer', 'Cloyd40@hotmail.com', 'Demi-man', '2025', '99259-6360');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Torrey', 'Hickle', 'Karen45@yahoo.com', 'Cis man', '1982', '12467-4009');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Arne', 'Koch', 'Gerhard.Kshlerin20@gmail.com', 'Female to male trans man', '1986', '79199');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shaylee', 'Yost', 'Enid94@hotmail.com', 'Gender variant', '1928', '31434');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Juliet', 'Kunde', 'Madyson.Kohler@hotmail.com', 'Agender', '1986', '03964-1279');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jammie', 'Ziemann', 'Aubrey.Lynch@hotmail.com', 'Pangender', '1986', '36648');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Junior', 'Hammes', 'Javon22@yahoo.com', 'Cis female', '2021', '43956');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Elmo', 'Stiedemann-Kertzmann', 'Kaylie_Kassulke@yahoo.com', 'Intersex person', '2022', '43293');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jasper', 'Carter', 'Jailyn39@hotmail.com', 'Polygender', '1989', '35677');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alvera', 'Okuneva', 'Edd.Boehm@hotmail.com', 'Gender fluid', '1927', '71285-3801');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maximillian', 'Smith', 'Norene.Nicolas79@hotmail.com', 'Transgender female', '2011', '50010-1183');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lora', 'Rice', 'Amari_Wehner@gmail.com', 'Demiflux', '1988', '13620');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Frederic', 'Bahringer', 'Lou64@gmail.com', 'Cis female', '1923', '27151');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rhoda', 'Cassin', 'Keyon_Greenholt22@hotmail.com', 'Male to female transgender woman', '2011', '75141-6830');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Liliana', 'Wunsch', 'Hal_Parisian2@gmail.com', 'Female to male', '1941', '11558');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Triston', 'Boehm', 'Talia17@yahoo.com', 'Transgender female', '1977', '87832');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Zoie', 'Kihn', 'Aisha1@gmail.com', 'Cis man', '1973', '54731');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Myrtie', 'Grady', 'Abbey_Heaney15@gmail.com', 'Gender nonconforming', '1937', '33674');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dallin', 'Schumm', 'Ebba34@yahoo.com', 'Transgender female', '1951', '11920');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ida', 'Sawayn', 'Randall_Bahringer43@hotmail.com', 'Male to female transsexual woman', '1938', '78970');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Coty', 'Kutch', 'Arjun.Oberbrunner@gmail.com', 'Trans female', '1991', '97051');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Edmund', 'Raynor', 'Carson.Kemmer@gmail.com', 'Neutrois', '1972', '19632');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Myrtie', 'Jacobi', 'Albina.Kassulke-Connelly@hotmail.com', 'Two* person', '1923', '89807');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lura', 'Sawayn', 'Kimberly_Kuhic@gmail.com', 'Bigender', '1978', '13033-2572');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jovanny', 'McLaughlin', 'Idell3@gmail.com', 'Neither', '2011', '66091-5639');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Scottie', 'Schmeler', 'Sydnie.Okuneva-Wilkinson12@gmail.com', 'T* man', '2007', '07376');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sandra', 'Bailey', 'Armani_OHara33@yahoo.com', 'Non-binary', '1959', '67055-0731');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brooks', 'Quigley', 'Catalina_Herzog5@yahoo.com', 'Demi-woman', '1971', '98277-5254');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kip', 'Hintz', 'Trever_Kiehn16@hotmail.com', 'Demi-woman', '2022', '95691');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Veronica', 'DuBuque', 'Johnny_Schiller86@yahoo.com', 'Trans', '1961', '04026-7142');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Elyse', 'Harvey-Schaden', 'Willa6@gmail.com', 'Man', '1924', '39588');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bridgette', 'Crist', 'Neha_Frami91@gmail.com', 'Transexual male', '1964', '12248');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sabryna', 'Labadie', 'Carole.Bahringer8@gmail.com', 'Transexual', '1991', '22594');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ramiro', 'Predovic', 'Frederic_Hirthe91@yahoo.com', 'Male to female', '2017', '59833');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bernadine', 'Maggio', 'Esteban77@hotmail.com', 'Cis female', '1975', '38660-6655');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jamar', 'Barrows', 'Kristian.Rippin19@hotmail.com', 'Female to male', '1995', '47528-6789');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Evie', 'Swift', 'Lori.Pollich30@hotmail.com', 'Genderflux', '1947', '40811-0150');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gillian', 'Oberbrunner', 'Finn26@yahoo.com', 'Two-spirit', '1938', '00081');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rashawn', 'Hettinger', 'Korey.Parker-Klein40@gmail.com', 'Male to female transsexual woman', '1990', '46682');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Conrad', 'Berge', 'Sven_McDermott@gmail.com', 'Gender neutral', '1979', '84291-7682');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Casper', 'Monahan', 'Marcella54@gmail.com', 'Gender variant', '1923', '87006');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jaleel', 'Bednar-Moore', 'Julian_Roberts78@yahoo.com', 'T* man', '2006', '78888');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Odell', 'Douglas', 'Bridgette_Fadel@gmail.com', 'Woman', '1933', '24153-0226');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shane', 'Metz', 'Cole61@yahoo.com', 'Cisgender man', '1953', '67090');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Neoma', 'Reynolds', 'Vince.Grady25@hotmail.com', 'Man', '2016', '13823');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tamara', 'Lemke', 'Adela.Stanton@hotmail.com', 'Demiflux', '1968', '83429-1533');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Domenic', 'Feeney', 'Carter.Grimes@yahoo.com', 'Gender neutral', '1998', '97685');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eulah', 'Zieme', 'Abigail.Orn@yahoo.com', 'Transexual male', '1940', '09707-4946');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Josh', 'Rodriguez-Corwin', 'Kathryn97@gmail.com', 'Demi-boy', '2017', '64910');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Orin', 'Rohan', 'Joshua.Roob20@yahoo.com', 'MTF', '1983', '36918');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Arnold', 'Bahringer', 'Chad_Haley@gmail.com', 'Genderflux', '2006', '89447-1058');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dimitri', 'Kunze', 'Whitney_Brekke@hotmail.com', 'Male to female transsexual woman', '1952', '67002');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Phoebe', 'Rutherford', 'Isabell94@yahoo.com', 'Male to female transsexual woman', '1963', '57290');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Abigail', 'Sauer', 'Jessica_Kutch92@hotmail.com', 'Man', '1981', '24558-4810');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Precious', 'Moen', 'Marge_Kertzmann15@yahoo.com', 'Gender nonconforming', '1943', '53888');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nathan', 'Block', 'Fleta_Koch@gmail.com', 'Gender fluid', '1936', '71855');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cassandre', 'Jast', 'Jocelyn.Flatley@yahoo.com', 'Trans man', '1944', '00917-1276');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Deven', 'McGlynn', 'Alanna46@gmail.com', 'Two* person', '1960', '09294');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dimitri', 'Bergnaum', 'Kacie_Zemlak82@hotmail.com', 'Transexual man', '2012', '43140-2015');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Austyn', 'Kunde', 'Cruz.Gerhold@yahoo.com', 'Cis male', '1965', '17742-9066');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eulah', 'Huels', 'Jasen_Walsh49@hotmail.com', 'Transgender female', '1959', '39578-4940');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gerry', 'Kub-Hand', 'Angelo_Sipes-Sawayn@gmail.com', 'M2F', '1937', '58566');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Vivienne', 'Oberbrunner', 'Ashlee_Jacobson@yahoo.com', 'Transexual person', '1954', '48613');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Otis', 'Koss', 'Theresia_Keeling@gmail.com', 'Demi-man', '1971', '46543');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tom', 'Skiles', 'Marlon19@hotmail.com', 'Neither', '1936', '78004-1905');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mallory', 'Dare', 'Lottie.Skiles80@yahoo.com', 'Female to male', '2003', '25224');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dell', 'Balistreri', 'Ethelyn_Kling54@gmail.com', 'Agender', '1955', '45710');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Casimer', 'Shanahan', 'Jon_Schumm89@hotmail.com', 'Neutrois', '1930', '75078');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Haley', 'Bode', 'Brian68@gmail.com', 'Gender variant', '2011', '39067-1397');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gerardo', 'Hammes', 'Eldred.Cormier73@hotmail.com', 'Bigender', '1967', '77875');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alexa', 'Hayes', 'Brooke.Goodwin@hotmail.com', 'Two* person', '1960', '08564-5450');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Giovanny', 'DuBuque', 'Misael.Wehner90@hotmail.com', 'Cis woman', '1980', '31489');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Julia', 'Stokes', 'Lupe.Brakus@gmail.com', 'Gender variant', '1947', '43116');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aryanna', 'Morar-Hermiston', 'Caroline.Ryan78@gmail.com', 'Female to male', '1975', '75746-9259');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lane', 'Murphy', 'Scarlett_Mayer@gmail.com', 'Transexual female', '2012', '99783');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Doyle', 'Hills', 'Hosea51@gmail.com', 'Gender nonconforming', '1926', '36901');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nella', 'Price', 'Hayley_Littel97@gmail.com', 'Transgender person', '1932', '38732');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Earnest', 'Bosco', 'Murl_Zboncak16@yahoo.com', 'Cisgender man', '2010', '98973');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Yesenia', 'Marvin', 'Mohamed70@yahoo.com', 'Demi-man', '2010', '81811');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jerel', 'Purdy', 'Jayden24@hotmail.com', 'Transgender person', '1997', '24102-8785');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ayden', 'Lemke-Marvin', 'Dorothy.Lockman@hotmail.com', 'Genderflux', '2014', '83409');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Anna', 'Kreiger', 'Brooklyn13@gmail.com', 'Trans woman', '1929', '78849-6619');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Augusta', 'Monahan', 'Alexanne.Marks@yahoo.com', 'Non-binary', '1922', '03826-1901');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Consuelo', 'Brekke-Hansen', 'Yasmine93@yahoo.com', 'FTM', '1959', '38171-0495');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nichole', 'Rolfson', 'Gunnar11@yahoo.com', 'M2F', '1935', '35838');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Amani', 'Schroeder', 'Sadye_Considine-Hayes40@yahoo.com', 'Male to female transsexual woman', '1997', '72008');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ellen', 'Glover', 'Beverly_Botsford@gmail.com', 'Female to male transgender man', '2002', '85191');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Fatima', 'Gulgowski', 'Destiney14@yahoo.com', 'MTF', '1928', '78693');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Vada', 'Nolan', 'Zane_Runte12@gmail.com', 'Trans', '1972', '15498');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Arno', 'Bosco', 'Kenneth.Jacobi38@yahoo.com', 'Demigender', '1936', '79315-9714');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shanelle', 'Macejkovic', 'Aubree.Wuckert69@gmail.com', 'Polygender', '1962', '85646');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aryanna', 'Kiehn', 'Carmel.Cummerata@yahoo.com', 'F2M', '1941', '38425');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Carlie', 'Rath-Schinner', 'Roosevelt_Rohan@gmail.com', 'Woman', '1951', '81093-6456');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Reyna', 'Hodkiewicz', 'Raul_Reilly90@hotmail.com', 'Demi-woman', '2018', '20802-2437');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Frankie', 'Ullrich', 'Janie29@yahoo.com', 'Demi-woman', '2018', '37831-3275');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cristal', 'Kemmer', 'Fiona93@hotmail.com', 'Gender fluid', '2013', '84190-1806');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Frederick', 'Stanton', 'Neva.Mitchell35@yahoo.com', 'Transgender person', '1950', '69446');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Patience', 'Bernier', 'Jeff.Cummerata45@gmail.com', 'Trans woman', '1929', '72828');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hans', 'Borer', 'Kellie42@hotmail.com', 'Neither', '2024', '47855-9049');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lyric', 'Schowalter', 'Mckenzie40@yahoo.com', 'F2M', '1991', '38056-0123');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tobin', 'Cruickshank', 'Isabell_Ward87@hotmail.com', 'Gender questioning', '2008', '79180-9643');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kyle', 'Collins', 'Eric.Kemmer@hotmail.com', 'Cisgender woman', '2000', '91866');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Elenor', 'Krajcik', 'Deja.Jerde@yahoo.com', 'Cisgender woman', '1932', '29448-8799');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kayley', 'Walker', 'Morton82@yahoo.com', 'Pangender', '1935', '51249');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Pamela', 'Barrows', 'Marvin63@yahoo.com', 'Gender variant', '2016', '92220');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Teresa', 'Klein', 'Dangelo.Hamill@hotmail.com', 'Male to female trans woman', '1948', '23251-7247');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nichole', 'Schmitt', 'Caesar.Jacobs8@hotmail.com', 'M2F', '1932', '38459');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sydnee', 'Stroman', 'Jamir.Barton7@yahoo.com', 'Demi-girl', '1976', '19351');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Morton', 'Ledner', 'Nicolette.Harvey-Torp57@yahoo.com', 'Male to female trans woman', '2018', '69671-7296');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Clara', 'Mosciski', 'Brenden.West56@gmail.com', 'Transexual', '1975', '87841');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Audreanne', 'White', 'Rubie_Hamill-Harris0@hotmail.com', 'Intersex', '2025', '70945');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Skylar', 'Schamberger', 'Earline.Pacocha@yahoo.com', 'Intersex', '2011', '04182-9508');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tina', 'Gleichner', 'Jakayla.Satterfield@yahoo.com', 'Two-spirit', '1939', '84814-0576');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Davonte', 'Schamberger', 'Alf.Konopelski@hotmail.com', 'Cis woman', '1967', '83842');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Esperanza', 'Casper', 'Halle.Langworth77@hotmail.com', 'Transgender person', '1989', '11781');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maverick', 'Thompson-Harris', 'Heather.McKenzie79@yahoo.com', 'Non-binary', '2021', '05265');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Petra', 'Dooley', 'Darryl_Rice91@gmail.com', 'Trans person', '1923', '49189');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alyson', 'Kozey', 'Damon_Mann81@gmail.com', 'Female to male transgender man', '1939', '67606');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Waino', 'Smith', 'Rusty.Walter56@yahoo.com', 'Xenogender', '1995', '98616-0766');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maxie', 'Torphy', 'Jaydon.OConnell@hotmail.com', 'Trigender', '1931', '81235');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Barbara', 'Thiel', 'Ozella39@gmail.com', 'Neither', '1922', '71792-4014');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Duncan', 'Bauch', 'Cordia_Kerluke45@hotmail.com', 'Cis male', '1963', '05594');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hayden', 'Strosin', 'Dusty_Deckow28@yahoo.com', 'Demi-man', '1922', '64039');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sabrina', 'Jenkins', 'Clemmie_Hamill63@gmail.com', 'T* woman', '1987', '12478');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Paige', 'Abernathy', 'Ned76@gmail.com', 'Trans person', '1995', '54602-6067');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Samantha', 'Crona', 'Clemmie.Zemlak@hotmail.com', 'Man', '2003', '80926-4424');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hudson', 'Ankunding', 'Luz70@yahoo.com', 'Transmasculine', '1944', '14242');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Theron', 'Becker', 'Rickey_Hermiston@gmail.com', 'Trans male', '1986', '81095-9150');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gennaro', 'Gutkowski', 'Sarah.Prosacco63@yahoo.com', 'Other', '1935', '10073');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Albin', 'Christiansen', 'Conor_Borer@gmail.com', 'Trans person', '1991', '21004');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Colleen', 'Wintheiser', 'Teresa58@hotmail.com', 'Pangender', '1929', '50631-5534');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Elton', 'Friesen', 'Iliana_Walker@gmail.com', 'Gender nonconforming', '2008', '46039');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Evalyn', 'Parisian', 'Mustafa_Kertzmann@gmail.com', 'F2M', '1980', '76491-4804');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kathryne', 'Emmerich', 'Anita50@yahoo.com', 'Transgender person', '1989', '35576-1645');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Johnathan', 'Reynolds', 'Katlyn91@hotmail.com', 'Gender questioning', '2005', '89380-5880');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cleo', 'Schoen', 'Laura_Bauch59@hotmail.com', 'Transmasculine', '1922', '61609-2995');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Talia', 'Leuschke', 'Lurline.Grimes72@yahoo.com', 'Omnigender', '1950', '54258-3336');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hailie', 'Dickens', 'Audra90@yahoo.com', 'Man', '1937', '68126');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Leslie', 'Schiller', 'Brain_Mann@hotmail.com', 'Male to female transgender woman', '1968', '57658');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Isaiah', 'Stroman', 'Guillermo.Rutherford@yahoo.com', 'Demi-boy', '1946', '77787');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Yasmine', 'Mante', 'Elvis76@gmail.com', 'Genderflux', '2008', '15335-3879');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Coralie', 'Ritchie', 'Kory.Hammes53@gmail.com', 'Male to female trans woman', '1922', '51357');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Joanne', 'Abshire', 'Jerrold.Sanford@gmail.com', 'Other', '2019', '17007');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Fritz', 'Balistreri', 'Augusta_Bogan@yahoo.com', 'Transgender female', '1936', '04796-7335');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Andy', 'Kiehn', 'Joana_Kerluke70@hotmail.com', 'Demi-girl', '1960', '79779');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Trinity', 'Jenkins', 'Leonel.Kulas@yahoo.com', 'Female to male transsexual man', '1938', '20267-7878');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Favian', 'Feeney-Thompson', 'Orion10@yahoo.com', 'Demi-boy', '1921', '86931-1410');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Laila', 'Haag', 'Porter36@gmail.com', 'Pangender', '1944', '92685-5660');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Leonel', 'Bechtelar', 'Bert_Jenkins@yahoo.com', 'Trans male', '2025', '59439-4108');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Madge', 'Hyatt', 'Adonis_Langworth@hotmail.com', 'Demigender', '1982', '43403-2772');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Reilly', 'Schmitt', 'Prudence.Kertzmann33@yahoo.com', 'Genderflux', '1941', '52075');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lionel', 'MacGyver', 'Javonte.Heller42@hotmail.com', 'Multigender', '1924', '40474-5941');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eldred', 'Kuphal', 'Rasheed_Breitenberg82@yahoo.com', 'Trans woman', '1955', '87193');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Courtney', 'Gibson-Schaden', 'Orval47@hotmail.com', 'Trans female', '2011', '96334');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Delphia', 'Brown', 'Name.Schulist63@yahoo.com', 'Androgyne', '1980', '96526-9512');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lemuel', 'Mayert', 'Lucy_Monahan@gmail.com', 'Transgender person', '1923', '27598');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kyler', 'Gerhold', 'Leola_Lowe@gmail.com', 'Demigender', '1965', '95785');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nicolas', 'Predovic-Veum', 'Easter.Marks@gmail.com', 'T* man', '1938', '39902-3906');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lexie', 'Herman', 'Sim65@gmail.com', 'Agender', '1924', '95264-7589');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ben', 'Stracke', 'Hardy_Schamberger24@gmail.com', 'Woman', '1976', '75726-1555');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rupert', 'Maggio', 'Leslie_Hoeger@hotmail.com', 'Cis male', '1982', '86655-4297');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Joan', 'Collier', 'Garland_Hammes23@hotmail.com', 'Intersex woman', '2006', '37457');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lisette', 'Pfannerstill', 'Randi.Crist@gmail.com', 'Intersex person', '1999', '75418-5897');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eugenia', 'Simonis-Hermiston', 'Osvaldo75@gmail.com', 'Intersex person', '1974', '05311-0154');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Berta', 'Turcotte', 'Cary_Goldner@yahoo.com', 'Androgynous', '2017', '19467');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gudrun', 'Emmerich', 'Carmen_Padberg@hotmail.com', 'Gender neutral', '2000', '41230');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Carter', 'Franey', 'Julie_Hartmann@hotmail.com', 'Omnigender', '1992', '43332-4069');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bernadine', 'Erdman', 'Jerad.Jones2@hotmail.com', 'Cisgender woman', '2021', '21058-7754');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bonita', 'Jones', 'Davin_Beier@yahoo.com', 'Two-spirit person', '1977', '18310-2513');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maddison', 'Skiles', 'Emmet50@gmail.com', 'Two-spirit person', '1990', '90950');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rosalia', 'Ritchie', 'Gail13@hotmail.com', 'Trans', '1921', '63029-0922');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kenton', 'Cruickshank-Gusikowski', 'Jacklyn95@gmail.com', 'Agender', '1999', '14584');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brooks', 'Hilll', 'Elaina71@gmail.com', 'Transexual person', '1993', '79747');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Idella', 'McLaughlin', 'Aniyah.Zemlak48@hotmail.com', 'Polygender', '1978', '38184');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Stan', 'Bailey', 'Ruben.Hettinger65@yahoo.com', 'Transgender female', '1977', '64504-1875');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marcia', 'Braun', 'Julian_Hills26@yahoo.com', 'Cisgender man', '1932', '86749-6010');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Aryanna', 'Konopelski', 'Maximus.Nader@hotmail.com', 'Neither', '1960', '80483');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cali', 'Lockman', 'Ariane18@gmail.com', 'Female to male transsexual man', '1935', '76335-7928');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Emelie', 'Daugherty', 'Dayna62@hotmail.com', 'Transexual female', '1939', '25548');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Levi', 'Gibson', 'Flossie0@yahoo.com', 'Demi-boy', '1961', '37999-0519');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Meda', 'Dach', 'Moises.Durgan@hotmail.com', 'T* woman', '1958', '40739-3818');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Makayla', 'Farrell', 'Frank77@hotmail.com', 'Demi-boy', '2000', '25416-2650');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Greg', 'Haley', 'Reggie_Mayer@hotmail.com', 'Gender neutral', '1951', '51648-0804');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mae', 'Bosco', 'Beaulah.Bergstrom89@gmail.com', 'Genderflux', '2012', '81569');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kenya', 'Bruen', 'Veda_Emmerich@gmail.com', 'Gender questioning', '1958', '97429');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Celestino', 'Ziemann', 'Tierra7@gmail.com', 'Hermaphrodite', '1995', '12304');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rosemarie', 'Quitzon', 'Mohammed88@hotmail.com', 'Transgender person', '1953', '37366');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Julius', 'Corwin', 'Malvina79@gmail.com', 'Androgynous', '1952', '65490-8459');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Naomi', 'Williamson', 'Terrance.Skiles@hotmail.com', 'Demigender', '2022', '93591-2339');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rae', 'Will', 'Whitney_Bode-Schmitt18@gmail.com', 'Two-spirit', '1986', '48001');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alec', 'Purdy', 'Bethany_Dach-McKenzie49@yahoo.com', 'Cis male', '1957', '09542-2381');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tess', 'Rohan', 'Armando.Gusikowski@hotmail.com', 'Transexual man', '2000', '27972-9539');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Clifford', 'Schultz', 'Alejandra_Smith14@gmail.com', 'Female to male transsexual man', '2001', '65990-8946');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rosalyn', 'Runte', 'Shanna88@yahoo.com', 'Cis man', '2003', '60952');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maximillia', 'Huels', 'Misael60@gmail.com', 'Gender nonconforming', '1972', '76256-4197');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jo', 'Rogahn', 'Bertrand.Rowe14@gmail.com', 'Gender fluid', '1981', '85834-8592');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Veda', 'Daniel-Nolan', 'Ellen.Emmerich95@yahoo.com', 'Demiflux', '1923', '46575-5004');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Estefania', 'Larson', 'Gayle10@yahoo.com', 'Multigender', '1963', '27173-7047');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mikel', 'Gutkowski', 'Herminio_Reinger@gmail.com', 'Intersex man', '2024', '09036-3322');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Katharina', 'Blick', 'Francisca60@gmail.com', 'Trans male', '1935', '53127');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Serena', 'Wyman', 'Nathen71@gmail.com', 'Demigender', '2023', '37768-5811');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Caitlyn', 'Lakin-Murphy', 'Teagan_Schroeder@gmail.com', 'Bigender', '1923', '38737-3940');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Collin', 'Bergnaum', 'Isabel.Halvorson57@gmail.com', 'Gender variant', '1946', '94381');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Evan', 'Glover', 'Dorthy_Jacobson98@hotmail.com', 'Trans male', '1921', '59853');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ethan', 'Ullrich', 'Florence93@yahoo.com', 'Trans', '1987', '45618');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Name', 'Roob', 'Neha_Hayes-Crona@gmail.com', 'Demi-woman', '2000', '45157-6969');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Demarcus', 'Fay', 'Bruce28@yahoo.com', 'Other', '2000', '15266-3893');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Linwood', 'Osinski', 'Hertha_DuBuque29@yahoo.com', 'Female to male trans man', '2024', '09505-2342');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nash', 'Rosenbaum', 'Ryann34@gmail.com', 'Cis woman', '1959', '90815');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jaclyn', 'Davis', 'Timmothy49@hotmail.com', 'Male to female', '2002', '65143-9219');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Geovanni', 'Predovic', 'Stacy_Will31@gmail.com', 'Cis', '1944', '77844-7315');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Nia', 'Miller', 'Akeem.Kassulke@hotmail.com', 'Demigender', '1997', '15946-2651');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Felipe', 'Barrows', 'Lucile29@hotmail.com', 'Gender variant', '2005', '18232');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alyson', 'Koepp', 'Audrey.Brakus@yahoo.com', 'Male to female transsexual woman', '2004', '91835-5307');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eleanora', 'Schmitt', 'Axel93@gmail.com', 'Trans person', '1928', '67803');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rafael', 'Lynch', 'Ozella_Simonis@yahoo.com', 'Gender variant', '2016', '30569');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Duncan', 'Braun', 'Martin98@gmail.com', 'Man', '1946', '56795');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mallory', 'Pouros', 'Angus8@yahoo.com', 'Gender fluid', '1981', '68836');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Randy', 'Weber', 'Lizzie38@hotmail.com', 'MTF', '1980', '18532');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Verdie', 'Bergnaum', 'Blaise_Berge@hotmail.com', 'Cisgender male', '1922', '04155-9422');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Orlo', 'Halvorson', 'Louisa.Tremblay@gmail.com', 'Cisgender female', '2006', '16861-0164');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bradley', 'Roob', 'Melba.Moen65@hotmail.com', 'Polygender', '1963', '42222-2624');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lorna', 'Grady', 'Emile60@gmail.com', 'Transexual man', '2011', '70105-2409');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Monte', 'Borer', 'Ashly_Emard@hotmail.com', 'Omnigender', '2020', '39531-3094');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sonia', 'Wisozk', 'Hubert_Kub@hotmail.com', 'Xenogender', '2007', '22331');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Geovanni', 'Stracke', 'Tiffany88@hotmail.com', 'F2M', '2017', '31705');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Osborne', 'Herman', 'Gonzalo34@gmail.com', 'Intersex', '2002', '46397-7009');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kurt', 'Zulauf', 'Emilio34@hotmail.com', 'F2M', '1998', '08345-9124');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rene', 'Swift', 'Art.Koss@yahoo.com', 'Bigender', '2016', '64607-8065');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Paxton', 'Grady', 'Jordyn45@yahoo.com', 'Neutrois', '1999', '32227');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kole', 'Harber', 'Torrance8@yahoo.com', 'Woman', '1967', '97035-9941');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Priscilla', 'Parisian', 'Hollie.Homenick@gmail.com', 'Male to female transsexual woman', '1924', '32952');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jayme', 'Koss', 'Dora.Renner@yahoo.com', 'Demi-man', '2017', '24500-3063');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Margret', 'Kreiger', 'Tiana.Brown@hotmail.com', 'Trans person', '1976', '00441');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Henderson', 'Torp', 'Myrtis_Lehner@gmail.com', 'Female to male trans man', '2025', '71671-8046');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lilly', 'Thiel', 'Augusta3@hotmail.com', 'Trans person', '1976', '26999-6650');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adalberto', 'Barrows', 'Zelma_Gutkowski92@yahoo.com', 'Neutrois', '1932', '95908-8289');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Emmett', 'Bahringer', 'Aliyah72@gmail.com', 'Neutrois', '2018', '21509-0431');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Berta', 'Labadie', 'Alexie_Lubowitz@hotmail.com', 'Androgyne', '1979', '16587');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dedric', 'Leuschke', 'Antonio_Cole@gmail.com', 'M2F', '1977', '48620');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Carmelo', 'Hintz', 'Vallie.Waters41@gmail.com', 'Cisgender female', '1980', '88084');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Margret', 'Herman', 'Gerson_Spinka16@hotmail.com', 'Trans female', '1956', '74001');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Octavia', 'Schimmel', 'Lane38@hotmail.com', 'Trans woman', '2023', '09757');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alanna', 'Frami', 'Stephen.Price@yahoo.com', 'F2M', '1987', '93894-1171');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maximus', 'Howe', 'Melvin.Kertzmann70@hotmail.com', 'Cisgender man', '1990', '33782');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Teagan', 'Dicki', 'Meda27@hotmail.com', 'Genderqueer', '2002', '73105');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Keira', 'Oberbrunner', 'Jermain_Feeney@gmail.com', 'Two-spirit', '1977', '90601-8423');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Darren', 'Rohan-Ritchie', 'Nelle.Hickle39@hotmail.com', 'Female to male transgender man', '1998', '93986-7250');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Josue', 'Robel', 'Eve86@yahoo.com', 'Gender questioning', '1921', '81416-0249');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Margaretta', 'Erdman', 'Malika.Medhurst67@gmail.com', 'Intersex woman', '1932', '03408-4903');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Wava', 'Kuhlman', 'Hermina.Aufderhar@yahoo.com', 'Cis woman', '2008', '64445-2958');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Titus', 'Harris', 'Shanel_Batz@yahoo.com', 'Hermaphrodite', '1965', '48934');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('John', 'Auer', 'Thalia56@hotmail.com', 'Intersex woman', '1976', '61604');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Camryn', 'Watsica', 'Thelma.McDermott49@yahoo.com', 'Two* person', '2025', '92818');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kurt', 'Huel', 'Adolf39@yahoo.com', 'Female to male transsexual man', '1953', '90560-3108');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Angelo', 'Schumm', 'Vanessa99@gmail.com', 'Trigender', '1940', '25050-6909');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marisa', 'Hoeger', 'Juvenal_Adams@yahoo.com', 'Gender questioning', '1946', '79671');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Delta', 'Konopelski', 'Chance_Parisian@hotmail.com', 'Pangender', '1997', '63744-4136');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tad', 'Stiedemann', 'Sydnie_Jaskolski52@hotmail.com', 'Cis', '1947', '88128-4477');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Caleb', 'Rowe', 'Elsa.Torphy@gmail.com', 'Cisgender man', '1992', '17293-6338');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shanie', 'Kreiger', 'Alaina.Conroy72@yahoo.com', 'MTF', '1948', '84311-8399');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jalyn', 'Gerhold', 'Ayana.Stanton98@yahoo.com', 'Trans male', '2003', '45133');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ambrose', 'Zboncak', 'Lane_Hauck53@gmail.com', 'Trigender', '2004', '72166');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Leann', 'Prosacco', 'Darien_Stanton@yahoo.com', 'Demi-girl', '1928', '91328-7613');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Annalise', 'Kautzer', 'Dennis.Ratke@gmail.com', 'T* man', '1968', '51597-8828');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tavares', 'Swaniawski', 'Christina_Schmitt78@hotmail.com', 'Intersex woman', '1952', '33121-6174');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Anais', 'Gusikowski', 'Josie22@gmail.com', 'T* man', '1976', '21428');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lauriane', 'Rau', 'Augusta_Barrows-Gulgowski19@hotmail.com', 'Two-spirit', '1938', '49619-7689');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Clemmie', 'Doyle', 'Tobin4@yahoo.com', 'Male to female trans woman', '1940', '64684');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ramona', 'Boehm-Mante', 'Terrence78@yahoo.com', 'Intersex man', '1983', '60522-4600');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Martine', 'Stroman', 'Beau_Lakin70@yahoo.com', 'Other', '2014', '76771-8455');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ken', 'Lakin', 'Rosie.Streich@yahoo.com', 'Trans person', '1949', '58238-9060');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marielle', 'Koch', 'Abner52@yahoo.com', 'Cisgender woman', '1974', '67094-8694');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Reagan', 'Kiehn', 'Brisa_Lakin@gmail.com', 'Polygender', '1985', '23744-2907');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rossie', 'Dietrich', 'Janiya.Klein61@gmail.com', 'Trans man', '1956', '90766');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Melissa', 'Koelpin', 'Kacey.Bechtelar@hotmail.com', 'Female to male trans man', '1934', '23892');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jessica', 'Bartoletti', 'Tony.Schumm@gmail.com', 'Demi-man', '1953', '04918');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Moriah', 'Lindgren', 'Betsy_Dare@hotmail.com', 'Demiflux', '1970', '59642-5935');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Brooklyn', 'Anderson-Trantow', 'Jacey.Beer19@gmail.com', 'Cis woman', '1998', '05697-5727');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Roosevelt', 'Sipes', 'Dianna71@hotmail.com', 'Cisgender female', '1929', '02564-4523');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Abel', 'Wisoky', 'Flavio_Runte52@hotmail.com', 'Transgender female', '2013', '13221');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adrienne', 'Yundt', 'Elyssa.Bartoletti@yahoo.com', 'Cis female', '1933', '91417');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kamryn', 'Botsford', 'Filiberto94@yahoo.com', 'Demiflux', '1994', '92177');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Noemie', 'Schinner', 'Kelley.Dietrich1@gmail.com', 'Cisgender', '2011', '85202');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Madalyn', 'Connelly', 'Germaine.Mertz@gmail.com', 'Transexual man', '1964', '46984');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bernhard', 'Wisoky', 'Maegan.Reynolds@yahoo.com', 'Cis male', '2022', '09433-2078');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Josiane', 'Hand', 'Milo69@yahoo.com', 'Intersex man', '1920', '01056-1045');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gerson', 'Wuckert', 'Lucy_Kozey@yahoo.com', 'Trans female', '1974', '61258-3594');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Mya', 'Schowalter', 'Genesis_Mueller@yahoo.com', 'Female to male transgender man', '1968', '89853');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jacky', 'Schroeder', 'Gustave.Wunsch@hotmail.com', 'Male to female transgender woman', '1959', '06312');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Viviane', 'Maggio', 'Corbin_Kub98@hotmail.com', 'Cisgender man', '1995', '79987-8073');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Randall', 'Sawayn', 'Merl_Krajcik@hotmail.com', 'Trans man', '1968', '41231-4837');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dave', 'Wiegand', 'Laurie_Kertzmann@hotmail.com', 'Androgyne', '1978', '37911');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Karley', 'Spencer', 'Rhiannon.Blanda-McGlynn37@yahoo.com', 'Female to male transgender man', '1929', '40819');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dayton', 'Grady', 'Eleonore.Ernser19@hotmail.com', 'Genderflux', '1956', '63836');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dylan', 'Lemke', 'Zoila.Quitzon34@gmail.com', 'Gender neutral', '1979', '98834');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dane', 'Cruickshank', 'Marlon52@hotmail.com', 'Two* person', '1959', '14033-9429');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Zakary', 'Hahn', 'Erik.Ryan91@gmail.com', 'Trans man', '2023', '28420');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Irma', 'Johnson-Simonis', 'Gregory41@yahoo.com', 'Cisgender', '1957', '03875-8380');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Orion', 'McLaughlin', 'Lucinda.Windler@hotmail.com', 'Androgynous', '1945', '82274');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cindy', 'Crona', 'Berta_Johnston12@yahoo.com', 'Cis woman', '2014', '25043');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Rylee', 'Stroman', 'Derrick.Powlowski28@yahoo.com', 'Intersex', '1984', '95286');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Scarlett', 'Ratke', 'Sincere42@yahoo.com', 'Intersex', '2014', '03514-6128');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Newell', 'Ortiz', 'Marco.Marquardt@yahoo.com', 'Hermaphrodite', '1986', '60021');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Camila', 'Kuphal', 'Ila65@gmail.com', 'Transgender female', '1993', '21264-9601');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Marc', 'Stokes', 'Hilton_Ziemann93@hotmail.com', 'T* woman', '1995', '58097-8680');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Asha', 'Hessel', 'Audra.Hane25@yahoo.com', 'T* woman', '2002', '34938-4626');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Damian', 'Breitenberg', 'Dewayne.Hirthe77@gmail.com', 'T* man', '2000', '05608');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Victor', 'Ruecker', 'Helmer.Kirlin-Fritsch13@hotmail.com', 'Bigender', '1937', '59347');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Justen', 'Emmerich-Hahn', 'Christelle_Kreiger@hotmail.com', 'Two-spirit person', '1993', '02426-8423');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Haylee', 'Bosco-McCullough', 'Jamarcus_Prohaska6@yahoo.com', 'Trans person', '1935', '70709-8559');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ladarius', 'Walker', 'Noble.Schmeler53@yahoo.com', 'Woman', '1965', '87219');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Harley', 'Keebler', 'Alanna_Simonis49@hotmail.com', 'Demigender', '2010', '11174');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Kyleigh', 'Swaniawski', 'Fredy_Dooley31@hotmail.com', 'Cis', '1957', '12212');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Zachery', 'Kshlerin', 'Camron32@yahoo.com', 'Intersex person', '1938', '73528');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Cale', 'Pouros', 'Lysanne82@hotmail.com', 'Neither', '1944', '74037');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Terrance', 'Corwin', 'Braden_Howe@gmail.com', 'Female to male', '1943', '42658-6213');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eldora', 'Ondricka', 'Karl93@gmail.com', 'Cis female', '1938', '06423-6181');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Zella', 'Bergstrom', 'Doris.Simonis77@yahoo.com', 'Intersex', '1982', '63828-2317');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Sidney', 'Kuhic', 'Valentin27@gmail.com', 'Gender neutral', '1989', '36006');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Tremayne', 'Watsica', 'Terrill80@yahoo.com', 'Cisgender female', '1946', '93512-7801');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Darrin', 'Hartmann', 'Otto_Hirthe@gmail.com', 'Intersex person', '1930', '61214-8907');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Laila', 'Pfannerstill', 'Abby.Kuphal49@hotmail.com', 'Gender neutral', '1940', '38145-4219');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Florence', 'Mante-Predovic', 'Katelynn.Runolfsson@yahoo.com', 'Pangender', '1990', '89169-6991');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Gerardo', 'Lockman', 'Thad.VonRueden41@gmail.com', 'Female to male transsexual man', '1988', '29696-5919');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Carmen', 'Reichert-Yost', 'Katlynn_Hessel@hotmail.com', 'Man', '1988', '86228-3059');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Wyatt', 'Wintheiser', 'Miguel53@hotmail.com', 'Male to female transgender woman', '1964', '84250-3675');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Clint', 'Cummerata', 'Dayana_Wisoky@yahoo.com', 'Transexual woman', '1964', '44104-1900');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Adaline', 'Moen', 'Paxton.Wilkinson90@hotmail.com', 'Gender questioning', '1983', '46449-9909');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Octavia', 'Reilly', 'Abbey.Hessel75@hotmail.com', 'Cis woman', '1955', '46791-0563');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Oswald', 'Jones', 'Kaci.Champlin@hotmail.com', 'Pangender', '1999', '89733');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Garnett', 'Gulgowski', 'Ole_Marvin@yahoo.com', 'Xenogender', '1925', '02657');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eleazar', 'Welch', 'Jackeline4@yahoo.com', 'Neither', '2016', '37947-5759');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Althea', 'Ratke', 'Joshuah_Stark52@gmail.com', 'Non-binary', '1972', '69360');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Virginia', 'Herzog', 'Leatha_Wehner59@hotmail.com', 'Trans', '1952', '48147');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lester', 'Kovacek', 'Harmony.Cruickshank@gmail.com', 'Gender variant', '1988', '43957-0375');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hiram', 'Roob', 'Ignacio.Corkery@yahoo.com', 'Intersex woman', '1948', '53889');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Monte', 'Kreiger', 'Darrick.Kohler33@yahoo.com', 'Gender questioning', '1968', '39446');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eldred', 'Mann', 'Deja_Prosacco@gmail.com', 'Demi-boy', '1970', '71004');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Demarcus', 'Schultz', 'Gardner15@gmail.com', 'Neutrois', '1955', '81759');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Arne', 'Zemlak', 'Antwan88@hotmail.com', 'Male to female', '1976', '95728');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Anna', 'Stamm', 'King.Ortiz56@gmail.com', 'Intersex woman', '1944', '62111');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Abe', 'Harris', 'Oswald83@hotmail.com', 'FTM', '1963', '77200-5073');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Abdul', 'Reichert', 'Ferne_Rice@gmail.com', 'Demi-woman', '1932', '14543');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Loyal', 'Block', 'Ed.Lowe96@hotmail.com', 'F2M', '1995', '73031-9713');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ivory', 'Predovic-Casper', 'Henriette_Vandervort@hotmail.com', 'Hermaphrodite', '1984', '44536-9592');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Micaela', 'Ward', 'Desiree.Braun23@gmail.com', 'Androgyne', '2024', '73841');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Deon', 'Batz-Robel', 'Susan27@gmail.com', 'Cisgender woman', '1950', '07540');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lily', 'Schmidt', 'Isabell_Pagac21@hotmail.com', 'Trans', '1981', '84386-4475');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shawn', 'Becker', 'Jena_Gislason47@hotmail.com', 'FTM', '1989', '83541-5370');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Warren', 'Bartoletti', 'Angelo31@yahoo.com', 'Cis male', '1929', '42188');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Layne', 'Cormier', 'Riley28@hotmail.com', 'Gender nonconforming', '1960', '29735');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Monserrate', 'Conroy', 'Sage.Hartmann42@yahoo.com', 'Two* person', '1951', '76878');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Garrison', 'Baumbach', 'Bradly.Kunze@gmail.com', 'Trigender', '1931', '65719-7968');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Duncan', 'Smitham', 'Precious_Waters31@yahoo.com', 'Female to male trans man', '1973', '89643');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Shanelle', 'Howell', 'Viola_Mann91@gmail.com', 'Transexual person', '1999', '36556');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Hettie', 'Bednar', 'Adelle.Anderson@gmail.com', 'Man', '2015', '76699');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Eleonore', 'Batz', 'Chadd77@yahoo.com', 'Transexual', '1978', '80360-3489');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Verner', 'Swaniawski', 'Stacy_Walter@yahoo.com', 'Cis male', '1936', '91792-7880');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Emilio', 'Gorczany', 'Angelita.Homenick@hotmail.com', 'Cis', '1954', '61755-1677');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Osvaldo', 'Crist', 'Annamae.Hartmann46@yahoo.com', 'Cis woman', '1992', '89593-0669');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Giles', 'Reinger', 'Hoyt52@yahoo.com', 'Xenogender', '1999', '25432');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Bridgette', 'Johns', 'Elissa15@hotmail.com', 'Transexual male', '1954', '42950');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Ciara', 'Cassin', 'Felicia59@gmail.com', 'Demi-woman', '1970', '60233-1789');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lazaro', 'Shanahan', 'Karianne13@hotmail.com', 'Transexual man', '1947', '04804');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Justina', 'Roob', 'Nakia45@yahoo.com', 'Demi-woman', '1945', '22306');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Jovani', 'Jacobson', 'Emmalee_Feeney51@gmail.com', 'Genderflux', '1988', '28213');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Israel', 'Shields', 'Else.Larkin@gmail.com', 'Gender neutral', '1931', '37588-6821');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Maryam', 'Johns', 'Brad.Mann@yahoo.com', 'Cisgender woman', '2005', '26332-8919');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Alvena', 'Labadie', 'Destini_Howe@yahoo.com', 'Female to male transgender man', '1927', '61479-5663');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Yasmeen', 'Beatty', 'Humberto57@gmail.com', 'Intersex', '1985', '01808-9469');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Paxton', 'Gulgowski', 'Fae44@yahoo.com', 'Demi-boy', '1984', '26084-7144');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Lizzie', 'Hickle', 'Alford34@hotmail.com', 'Intersex man', '1947', '39684-3179');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Daisy', 'Homenick', 'Stephany15@yahoo.com', 'Hermaphrodite', '1999', '62551-2707');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Melany', 'Pfeffer', 'Gayle_Jacobson@yahoo.com', 'Cisgender woman', '2018', '02945');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Asha', 'Rice', 'Jewell.Weissnat83@hotmail.com', 'Transexual man', '1986', '02940-2640');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Florian', 'Heaney', 'Faustino_Davis@gmail.com', 'Transmasculine', '1949', '89532');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Delphine', 'Osinski', 'Bonnie.Durgan70@gmail.com', 'Transexual man', '1947', '13036-6739');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Taryn', 'Rolfson', 'Georgiana_Haag-Rodriguez84@gmail.com', 'Pangender', '1967', '68134-4605');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Wyman', 'Schoen', 'Rylee_Hane33@yahoo.com', 'Female to male', '1996', '47980');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Dayne', 'Haley', 'Warren_Goyette-OConnell97@hotmail.com', 'Non-binary', '1968', '15059-8919');
INSERT INTO users (nome, sobrenome, email, genero, anoNascimento, cpf) VALUES ('Luis', 'Effertz', 'Dorian23@gmail.com', 'Androgyne', '1939', '42060-4080');